Repository pinterest/thriftcheck, pull requests merged in 2023-02, with the labels that each got.

#61 🚩 add struct field comment check
  README.md
  checks/fields.go
  checks/fields_test.go
  cmd/main.go
Labels: enhancement

#57 Remove 'skip-go-installation'
  .github/workflows/ci.yml
Labels: github_actions

#58 Upgrade to testify version 1.8.1 (from 1.7.1)
  go.mod
  go.sum
Labels: dependencies
